// <auto-generated />
using System;
using DataAccess.Provider.SQLite.LocalKioskDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Provider.SQLite.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20251114141734_UpdateOrderTableProductId")]
    partial class UpdateOrderTableProductId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("LegacyOrderService.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LegacyOrderService.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Widget",
                            Price = 12.99m,
                            RegistrationDate = new DateTime(2025, 11, 14, 14, 17, 33, 982, DateTimeKind.Utc).AddTicks(5806),
                            Status = 0
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Gadget",
                            Price = 15.49m,
                            RegistrationDate = new DateTime(2025, 11, 14, 14, 17, 33, 982, DateTimeKind.Utc).AddTicks(5809),
                            Status = 0
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Doohickey",
                            Price = 8.75m,
                            RegistrationDate = new DateTime(2025, 11, 14, 14, 17, 33, 982, DateTimeKind.Utc).AddTicks(5811),
                            Status = 2
                        });
                });

            modelBuilder.Entity("LegacyOrderService.Models.Order", b =>
                {
                    b.HasOne("LegacyOrderService.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LegacyOrderService.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
